### ISSUE TITLE
Cannot convert with Tensorflow1.0 installed by virtualenv

### ISSUE THREAD

**Issue by guo253** [ethereon/caffe-tensorflow#103]
Hi, I got an error of "TypeError: Descriptors should not be created directly, but only retrieved from their parent." when convert the caffemodel.
Following were my steps:

#activate the tf 1.0
source bin/activate 

(tensorflow_1) erbu@erbu-NF5568M4:~/code/tensorflow/tensorflow_1/caffe-tensorflow$ ./convert.py models/VGG_ILSVRC_16_layers_deploy.prototxt --code-output-path=my.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "./convert.py", line 60, in <module>
    main()
  File "./convert.py", line 56, in main
    args.phase)
  File "./convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/erbu/code/tensorflow/tensorflow_1/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/erbu/code/tensorflow/tensorflow_1/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/erbu/code/tensorflow/tensorflow_1/caffe-tensorflow/kaffe/graph.py", line 140, in __init__
    self.load()
  File "/home/erbu/code/tensorflow/tensorflow_1/caffe-tensorflow/kaffe/graph.py", line 144, in load
    self.params = get_caffe_resolver().NetParameter()
  File "/home/erbu/code/tensorflow/tensorflow_1/caffe-tensorflow/kaffe/caffe/resolver.py", line 32, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "/home/erbu/code/tensorflow/tensorflow_1/caffe-tensorflow/kaffe/caffe/resolver.py", line 7, in __init__
    self.import_caffe()
  File "/home/erbu/code/tensorflow/tensorflow_1/caffe-tensorflow/kaffe/caffe/resolver.py", line 17, in import_caffe
    from . import caffepb
  File "/home/erbu/code/tensorflow/tensorflow_1/caffe-tensorflow/kaffe/caffe/caffepb.py", line 28, in <module>
    type=None),
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 649, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

ps:
(tensorflow_1) erbu@erbu-NF5568M4:~/code/tensorflow/tensorflow_1/caffe-tensorflow$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google import protobuf
>>> protobuf.__version__
'3.2.0'

Thank you very much!

**Comment by yuanming-hu** [comment]
I tried protobuf 3.2.0, 3.0.0, 2.6.1 and unfortunately none of them works. I can not import caffepb with 3.2.0 or 3.0.0, while 2.6.1 will cause the tensorflow error (tf version 1.0.0rc2).

**Comment by simo23** [comment]
Same here, I've just installed Tensorflow 1.3 with virtualenv and caffe but it gives this error.

`Traceback (most recent call last):
  File "convert.py", line 60, in <module>
    main()
  File "convert.py", line 56, in main
    args.phase)
  File "convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/simo/Desktop/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/simo/Desktop/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/simo/Desktop/caffe-tensorflow/kaffe/graph.py", line 140, in __init__
    self.load()
  File "/home/simo/Desktop/caffe-tensorflow/kaffe/graph.py", line 144, in load
    self.params = get_caffe_resolver().NetParameter()
  File "/home/simo/Desktop/caffe-tensorflow/kaffe/caffe/resolver.py", line 32, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "/home/simo/Desktop/caffe-tensorflow/kaffe/caffe/resolver.py", line 7, in __init__
    self.import_caffe()
  File "/home/simo/Desktop/caffe-tensorflow/kaffe/caffe/resolver.py", line 17, in import_caffe
    from . import caffepb
  File "/home/simo/Desktop/caffe-tensorflow/kaffe/caffe/caffepb.py", line 28, in <module>
    type=None),
  File "/home/simo/virtualtensorflow/local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 654, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
`
Any updates on this?

**Comment by simo23** [comment]
Looking again I found the solution in the issues: 

https://github.com/ethereon/caffe-tensorflow/issues/114 

This solved the problem! I think @ethereon this issue can be closed now.
