### ISSUE TITLE
google.protobuf.text_format.ParseError: 19:3 : Message type "caffe.LayerParameter" has no field named "bn_param".

### ISSUE THREAD

**Issue by mikeleatila** [ethereon/caffe-tensorflow#118]
Hello, 

I am a beginner to Caffe/TensorFlow/Python. I want to convert existing Caffe's .prototxt to TensorFlow using convert.py, i.e. when running: 

root@0352fe53b2be:/src/temporal-segment-networks/lib/caffe-tensorflow-master# ./convert.py /src/temporal-segment-networks/models/ucf101/test1.prototxt --code-output-path=test.py

I get following error:

------------------------------------------------------------
    WARNING: PyCaffe not found!
    Falling back to a pure protocol buffer implementation.
    * Conversions will be drastically slower.
    * This backend is UNTESTED!
------------------------------------------------------------

Traceback (most recent call last):
  File "./convert.py", line 60, in <module>
    main()
  File "./convert.py", line 56, in main
    args.phase)
  File "./convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/src/temporal-segment-networks/lib/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/src/temporal-segment-networks/lib/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/src/temporal-segment-networks/lib/caffe-tensorflow-master/kaffe/graph.py", line 140, in __init__
    self.load()
  File "/src/temporal-segment-networks/lib/caffe-tensorflow-master/kaffe/graph.py", line 146, in load
    text_format.Merge(def_file.read(), self.params)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 476, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 526, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 559, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 574, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 643, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 19:3 : Message type "caffe.LayerParameter" has no field named "bn_param".
root@0352fe53b2be:/src/temporal-segment-networks/lib/caffe-tensorflow-master# google.protobuf.text_format.ParseError: 19:3 : Message type "caffe.LayerParameter" has no field named "bn_para   

Anyone has any ideas about it? Many thanks in advance!

M

**Comment by mikeleatila** [comment]
This has been fixed.

**Comment by rimassouel** [comment]
How has it been fixed ? I have pretty much the same problem here ..

**Comment by mikeleatila** [comment]
Hello, 

I needed to replace "bn_param" parameter in Caffe's prototxt format to "batch_norm_param". This was changed from "bn_param" - please have a look at:

https://github.com/BVLC/caffe/commit/a52ee656a589313901560c87b65a570ee41c9fee#diff-e0bd8d028edf0f88febfebe3bf703904R353

Best,

M

**Comment by YilanWang** [comment]
hello! thanks to your link, but in my model the 'bn_param' has a parameter 'frozen', however in 'batch_norm_param' there is no 'frozen'. do you have any ways to solve it? thx~

**Comment by lrhjw** [comment]
hello , I have the same problem ,had you work out it, thanks

**Comment by mikeleatila** [comment]
I have not faced this issue, thus I don't know, sorry.

**Comment by lrhjw** [comment]
thanks
