### ISSUE TITLE
Error with 1-d model

### ISSUE THREAD

**Issue by RamyaNT** [ethereon/caffe-tensorflow#12]
Hi,
I'm trying to convert a model trained on MNIST in caffe. The conversion to tensorflow is raising an error. The conversion utility is missing the number of channels param for the first Convolution layer. Instead of reading the 4d array as (64, 1, 5, 5) for Conv1 layer, it only recognizes the params as a 3d array viz., (64, 5, 5). Can you pls help me.

Regards

**Comment by ethereon** [comment]
I'd need to look at the model definition to debug this. Is this publicly available? If not, could you paste the block corresponding to Conv1?

**Comment by RamyaNT** [comment]
Please look into the model and the block corresponding to the above issue
Type                 Name                                          Param               Output
----------------------------------------------------------------------------------------------
Data                 data                                             --      (64, 1, 28, 28)
Convolution          conv1                                     (64, 5, 5)      (64, 8, 24, 24)
Pooling              pool1                                            --      (64, 8, 12, 12)
Convolution          conv2                                 (16, 8, 5, 5)       (64, 16, 8, 8)
Pooling              pool2                                            --       (64, 16, 4, 4)
InnerProduct         ip1                                      (128, 256)      (64, 128, 1, 1)
InnerProduct         ip2                                       (10, 128)       (64, 10, 1, 1)
Softmax              prob                                             --       (64, 10, 1, 1)
Converting data...
Traceback (most recent call last):
  File "local/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/convert.py", line 33, in <module>
    main()
  File "local/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/convert.py", line 19, in main
    data = transformer.transform_data()
  File "/home/ramyant/tensorflow/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 199, in transform_data
    self.transform_source()        
  File "/home/ramyant/tensorflow/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 208, in transform_source
    chains = mapper.map()
  File "/home/ramyant/tensorflow/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/kaffe/core.py", line 348, in map
    mapped_chains.append(self.map_chain(chain))
  File "/home/ramyant/tensorflow/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/kaffe/core.py", line 352, in map_chain
    return [self.map_node(node) for node in chain]
  File "/home/ramyant/tensorflow/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/kaffe/core.py", line 356, in map_node
    mapped_node = map_func(node)
  File "/home/ramyant/tensorflow/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 63, in map_convolution
    (c_o, c_i, h, w) = node.data_shape
ValueError: need more than 3 values to unpack

Regards

**Comment by ethereon** [comment]
I meant the Caffe model definition (the one in the .prototxt file).However, I think I know what's causing the problem. The protobuf backend had a stray squeeze call that was clobbering the singleton dimensions. I've pushed an update that should fix it. Let me know if it works.

**Comment by RamyaNT** [comment]
It seems to have worked with Conv1 layer, but seems to have some issue with the dimensions of the params  of FC layer. The FC layer's weight dimensions were appended and transformed into a 4d array. The result is

Type                 Name                                          Param               Output
----------------------------------------------------------------------------------------------
Data                 data                                             --      (64, 1, 28, 28)
Convolution          conv1                                  (64, 1, 5, 5)      (64, 8, 24, 24)
Pooling              pool1                                            --      (64, 8, 12, 12)
Convolution          conv2                                 (16, 64, 5, 5)       (64, 16, 8, 8)
Pooling              pool2                                            --       (64, 16, 4, 4)
InnerProduct         ip1                                (1, 1, 128, 256)      (64, 128, 1, 1)
InnerProduct         ip2                                 (1, 1, 10, 128)       (64, 10, 1, 1)
Softmax              prob                                             --       (64, 10, 1, 1)
Converting data...
Traceback (most recent call last):
  File "local/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/convert.py", line 33, in <module>
    main()
  File "local/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/convert.py", line 19, in main
    data = transformer.transform_data()
  File "/home/ramyant/tensorflow/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 202, in transform_data
    DataReshaper(mapping).reshape(self.graph)
  File "/home/ramyant/tensorflow/lib/python2.7/site-packages/tensorflow/caffe-tensorflow/kaffe/core.py", line 196, in reshape
    data = data.reshape((fc_shape[IDX_C_OUT], in_shape[IDX_C], in_shape[IDX_H], in_shape[IDX_W]))
ValueError: total size of new array must be unchanged

Regards

**Comment by ethereon** [comment]
I've pushed a new version which should fix the issues with the FC layer.

Note that these issues are restricted to the protobuf backend only. Everything should already work correctly with the PyCaffe backend.

**Comment by RamyaNT** [comment]
Yes, that worked like a charm. Happy new year to you.
Regards
