### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by arnaudmiribel** [ethereon/caffe-tensorflow#120]
Hi there,

On Ubuntu with a python3 environment, I'm trying to convert VGG16-hybrid365 weights from [here](https://github.com/CSAILVision/places365). (Someone did it already?)

First had an issue with `text.split` error, so I used the trick to change `rb` to `b` as seen in that [issue](https://github.com/ethereon/caffe-tensorflow/issues/102). Apparently was just a python3 vs 2 problem.

Now I run into something else when calling `convert.py` : 

My command 

```
python convert.py ../deploy_vgg16_hybrid1365.prototxt --code-output-path ./code_output/ --caffemodel ../vgg16_hybrid1365.caffemodel --data-output-path ./data_output/
``` 

Output 

```
Traceback (most recent call last):
  File "convert.py", line 60, in <module>
    main()
  File "convert.py", line 56, in main
    args.phase)
  File "convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/ubuntu/work/scene/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/ubuntu/work/scene/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/ubuntu/work/scene/caffe-tensorflow/kaffe/graph.py", line 140, in __init__
    self.load()
  File "/home/ubuntu/work/scene/caffe-tensorflow/kaffe/graph.py", line 146, in load
    text_format.Merge(def_file.read(), self.params)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 476, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 526, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 559, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 574, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 619, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 1066, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number.')
google.protobuf.text_format.ParseError: 7:1 : Expected identifier or number.
```

Not quite sure how to overcome this though...

**Comment by arnaudmiribel** [comment]
Ok got it. I did a `wget` on a GitHub link for a `.txt` file but it pointed to the actual HTML page and not the raw `.txt` page. So the problem above comes from a broken `deploy_vgg16_hybrid1365.prototxt` !

**Comment by EvenOldridge** [comment]
Thanks.  I ran into the exact same issue. (I'm also trying to convert places365).

@arnaudmiribel Have you had any luck there?

I made it to the next step which for me was an "TypeError: unsupported format string passed to tuple.__format__" error.

**Comment by BinhangYuan** [comment]
Same question here:

Traceback (most recent call last):
  File "D:/Binhang/caffe-tensorflow-master/convert.py", line 60, in <module>
    main()
  File "D:/Binhang/caffe-tensorflow-master/convert.py", line 56, in main
    args.phase)
  File "D:/Binhang/caffe-tensorflow-master/convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "D:\Binhang\caffe-tensorflow-master\kaffe\tensorflow\transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "D:\Binhang\caffe-tensorflow-master\kaffe\tensorflow\transformer.py", line 254, in load
    print_stderr(self.graph)
  File "D:\Binhang\caffe-tensorflow-master\kaffe\errors.py", line 7, in print_stderr
    sys.stderr.write('%s\n' % msg)
  File "D:\Binhang\caffe-tensorflow-master\kaffe\graph.py", line 125, in __str__
    s.append('{:<20} {:<30} {:>20} {:>20}'.format(node.kind, node.name, data_shape, tuple(out_shape)))
TypeError: unsupported format string passed to tuple.__format__
