### ISSUE TITLE
MNIST convert example fails with ImportError

### ISSUE THREAD

**Issue by johnsrude** [ethereon/caffe-tensorflow#134]
When I run:
```$ ./convert.py examples/mnist/lenet.prototxt --code-output-path=mynet.py```

I get:

```
caffe-tensorflow-master$ ./convert.py examples/mnist/lenet.prototxt --code-output-path=mynet.py
Traceback (most recent call last):
  File "/home/kevin/Deadpool/Convert/caffe-tensorflow-master/kaffe/caffe/resolver.py", line 13, in import_caffe
    import caffe
  File "/home/gradescan/caffe-segnet/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/gradescan/caffe-segnet/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: libprotobuf.so.8: cannot open shared object file: No such file or directory
```

but protobuf is up-to-date:

```
 pip install protobuf
Requirement already satisfied: protobuf in /usr/local/share/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: six>=1.9 in /usr/local/share/anaconda3/lib/python3.6/site-packages (from protobuf)
Requirement already satisfied: setuptools in /usr/local/share/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg (from protobuf)

```

I next installed conda.  And I installed the binary version of caffe per instructions at http://caffe.berkeleyvision.org/install_apt.html.  I now get the error

```
  ./caffe-tensorflow-master/convert.py caffe-models/lenet.prototxt --code-output-path=lenet.py
Traceback (most recent call last):
  File "./caffe-tensorflow-master/convert.py", line 7, in <module>
    from kaffe import KaffeError, print_stderr
  File "/home/kevin/Deadpool/Convert/caffe-tensorflow-master/kaffe/__init__.py", line 1, in <module>
    from .graph import GraphBuilder, NodeMapper
  File "/home/kevin/Deadpool/Convert/caffe-tensorflow-master/kaffe/graph.py", line 1, in <module>
    from google.protobuf import text_format
ModuleNotFoundError: No module named 'google'
```

**Comment by johnsrude** [comment]
upgraded to ubuntu 17 to fix linking issue
