### ISSUE TITLE
tf.split() and tf.concat() parameter order

### ISSUE THREAD

**Issue by entalent** [ethereon/caffe-tensorflow#141]
Initializing network with tensorflow 1.2.1 leads to such error:
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    net = CaffeNet({'data': input_data})
  File "/home/caffe-tensorflow/kaffe/tensorflow/network.py", line 47, in __init__
    self.setup()
  File "/home/caffe-tensorflow/test.py", line 9, in setup
    .conv(5, 5, 256, 1, 1, group=2, name='conv2')
  File "/home/caffe-tensorflow/kaffe/tensorflow/network.py", line 21, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/caffe-tensorflow/kaffe/tensorflow/network.py", line 133, in conv
    input_groups = tf.split(3, group, input)
  File "/home/library/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1214, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/library/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3261, in _split
    num_split=num_split, name=name)
  File "/home/library/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.
```

This occurs at kaffe/tensorflow/network.py, line 133 and 134:
```python
input_groups = tf.split(3, group, input)
kernel_groups = tf.split(3, group, kernel)
```

It seems that the default parameter order of tf.split() changed after tensorflow v0.12, and calling tf.split() without specifying parameter's name would cause the error. I then changed them to 
```python
input_groups = tf.split(axis=3, num_or_size_splits=group, value=input)
kernel_groups = tf.split(axis=3, num_or_size_splits=group, value=kernel)
```
and those lines run correctly...

The same thing happens with line 137:
```python
output = tf.concat(3, output_groups)
```
And I think this should be changed to 
```python
output = tf.concat(axis=3, values=output_groups)
```

**Comment by dreamibor** [comment]
That's great! I got the same problem too.
