### ISSUE TITLE
Unable to determine kernel parameter!

### ISSUE THREAD

**Issue by LiuHao-THU** [ethereon/caffe-tensorflow#150]
when i try to convert caffe model to tensorflow model i met this problem, how can i solve this problem

**Comment by LiuHao-THU** [comment]
Traceback (most recent call last):
  File "convert.py", line 60, in <module>
    main()
  File "convert.py", line 56, in main
    args.phase)
  File "convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/lh/Desktop/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/lh/Desktop/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/lh/Desktop/caffe-tensorflow-master/kaffe/graph.py", line 255, in build
    graph.compute_output_shapes()
  File "/home/lh/Desktop/caffe-tensorflow-master/kaffe/graph.py", line 99, in compute_output_shapes
    node.output_shape = TensorShape(*NodeKind.compute_output_shape(node))
  File "/home/lh/Desktop/caffe-tensorflow-master/kaffe/layers.py", line 69, in compute_output_shape
    val = LAYER_DESCRIPTORS[node.kind](node)
  File "/home/lh/Desktop/caffe-tensorflow-master/kaffe/shapes.py", line 78, in shape_pool
    return get_strided_kernel_output_shape(node, math.ceil)
  File "/home/lh/Desktop/caffe-tensorflow-master/kaffe/shapes.py", line 19, in get_strided_kernel_output_shape
    node.layer.kernel_parameters, round_func)
  File "/home/lh/Desktop/caffe-tensorflow-master/kaffe/layers.py", line 137, in kernel_parameters
    k_h = self.get_kernel_value(params.kernel_h, params.kernel_size, 0)
  File "/home/lh/Desktop/caffe-tensorflow-master/kaffe/layers.py", line 130, in get_kernel_value
    raise ValueError('Unable to determine kernel parameter!')
ValueError: Unable to determine kernel parameter!

**Comment by tranui12** [comment]
Did you resolve this issue?
