### ISSUE TITLE
error: TypeError: Descriptors should not be created directly, but only retrieved from their parent.

### ISSUE THREAD

**Issue by mokii** [ethereon/caffe-tensorflow#153]
What is wrong with my code?
When I convert the Deeplab caffe model to tensorflow : 
`python convert.py ../DeepLab_LargeFOV/test.prototxt --caffemodel ../DeepLab_LargeFOV/train2_iter_8000.caffemodel --data-output-path ../DeepLab_LargeFOV/DeepLab_LargeFOV-model.ckpt` 
I get the following error:
`Traceback (most recent call last):
  File "convert.py", line 60, in <module>
    main()
  File "convert.py", line 56, in main
    args.phase)
  File "convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/mokii/semantic_segmentation/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/mokii/semantic_segmentation/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/mokii/semantic_segmentation/caffe-tensorflow-master/kaffe/graph.py", line 140, in __init__
    self.load()
  File "/home/mokii/semantic_segmentation/caffe-tensorflow-master/kaffe/graph.py", line 144, in load
    self.params = get_caffe_resolver().NetParameter()
  File "/home/mokii/semantic_segmentation/caffe-tensorflow-master/kaffe/caffe/resolver.py", line 32, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "/home/mokii/semantic_segmentation/caffe-tensorflow-master/kaffe/caffe/resolver.py", line 7, in __init__
    self.import_caffe()
  File "/home/mokii/semantic_segmentation/caffe-tensorflow-master/kaffe/caffe/resolver.py", line 17, in import_caffe
    from . import caffepb
  File "/home/mokii/semantic_segmentation/caffe-tensorflow-master/kaffe/caffe/caffepb.py", line 28, in <module>
    type=None),
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 654, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
`

**Comment by mokii** [comment]
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google import protobuf
>>> protobuf.__version__
'3.5.0.post1'
>>> import caffepb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named caffepb

**Comment by mokii** [comment]
Solved this problem as #10
