### ISSUE TITLE
Message type "caffe.LayerParameter" has no field named "augmentation_param".

### ISSUE THREAD

**Issue by yellowYuga** [ethereon/caffe-tensorflow#157]
```
Traceback (most recent call last):
  File "./convert.py", line 60, in <module>
    main()
  File "./convert.py", line 56, in main
    args.phase)
  File "./convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/hyj/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/hyj/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/hyj/caffe-tensorflow-master/kaffe/graph.py", line 140, in __init__
    self.load()
  File "/home/hyj/caffe-tensorflow-master/kaffe/graph.py", line 146, in load
    text_format.Merge(def_file.read(), self.params)
  File "/home/hyj/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/google/protobuf/text_format.py", line 525, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/hyj/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/google/protobuf/text_format.py", line 579, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/hyj/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/google/protobuf/text_format.py", line 612, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/hyj/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/google/protobuf/text_format.py", line 627, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/hyj/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/google/protobuf/text_format.py", line 727, in _MergeField
    merger(tokenizer, message, field)
  File "/home/hyj/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/google/protobuf/text_format.py", line 815, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/hyj/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/google/protobuf/text_format.py", line 695, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 66:3 : Message type "caffe.LayerParameter" has no field named "augmentation_param".





Here are some codes in my prototxt:

layer {
  name: "img0s_aug"
  type: "DataAugmentation"
  bottom: "img0s"
  top: "img0_nomean"
  augmentation_param {
    augment_during_test: true
    recompute_mean: 1000
    mean_per_pixel: false
    crop_width: $TARGET_WIDTH
    crop_height: $TARGET_HEIGHT
  }
}

**Comment by Genlk** [comment]
I met the same problem

**Comment by YCakira** [comment]
这是来自QQ邮箱的自动回复邮件。嗨，这里是吴颖的信箱。谢谢你的来信，我将会尽快给你回复。
