### ISSUE TITLE
failed to run "./convert.py examples/mnist/lenet.prototxt --code-output-path=mynet.py"

### ISSUE THREAD

**Issue by scottyyih** [ethereon/caffe-tensorflow#163]
Here is the error message. Can anybody tell me what's wrong?

caffe-tensorflow$ ./convert.py examples/mnist/lenet.prototxt --code-output-path=mynet.py
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./convert.py", line 60, in <module>
    main()
  File "./convert.py", line 56, in main
    args.phase)
  File "./convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/scottyyi/MachineLearning/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/scottyyi/MachineLearning/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/scottyyi/MachineLearning/caffe-tensorflow/kaffe/graph.py", line 140, in __init__
    self.load()
  File "/home/scottyyi/MachineLearning/caffe-tensorflow/kaffe/graph.py", line 144, in load
    self.params = get_caffe_resolver().NetParameter()
  File "/home/scottyyi/MachineLearning/caffe-tensorflow/kaffe/caffe/resolver.py", line 32, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "/home/scottyyi/MachineLearning/caffe-tensorflow/kaffe/caffe/resolver.py", line 7, in __init__
    self.import_caffe()
  File "/home/scottyyi/MachineLearning/caffe-tensorflow/kaffe/caffe/resolver.py", line 17, in import_caffe
    from . import caffepb
  File "/home/scottyyi/MachineLearning/caffe-tensorflow/kaffe/caffe/caffepb.py", line 28, in <module>
    type=None),
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 654, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

**Comment by hwandy94** [comment]
https://stackoverflow.com/questions/38616620/caffe-to-tensorflow-kaffe-by-ethereon-typeerror-descriptors-should-not-be-c
I have the same problem and now it's solved. I refer to this discussion for the answer. Simply changing "kaffe/caffe/caffepb.py" to "kaffe/caffe/caffe_pb2.py" and changing the import code inside "kaffe/caffe/resolver.py:"
`
line 17: from . import caffepb => from . import caffe_pb2
`
`
line 18: self.caffepb = caffepb => self.caffepb = caffe_pb2
`
and remember to delete caffepb.pyc and resolver.pyc files after change; otherwise, the old pyc file will be used. 

After this, I have met another bug showing an error using internal protobuf. I solved it by installing caffe and pycaffe.
