### ISSUE TITLE
failed to run "./convert.py examples/mnist/lenet.prototxt --code-output-path=mynet.py"

### ISSUE THREAD

**Issue by dinglong1020** [ethereon/caffe-tensorflow#164]
environment： ubuntu1604 python2.7 tensorflow1.6（only cpu）

(tensorflow) ubuntu@vm:~/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow$ ./convert.py examples/mnist/lenet.prototxt --code-output-path=mynet.py
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./convert.py", line 60, in <module>
    main()
  File "./convert.py", line 56, in main
    args.phase)
  File "./convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/graph.py", line 140, in __init__
    self.load()
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/graph.py", line 144, in load
    self.params = get_caffe_resolver().NetParameter()
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/caffe/resolver.py", line 32, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/caffe/resolver.py", line 7, in __init__
    self.import_caffe()
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/caffe/resolver.py", line 23, in import_caffe
    self.caffepb = self.caffe.proto.caffe_pb2
AttributeError: 'module' object has no attribute 'proto'

**Comment by dinglong1020** [comment]
(tensorflow) ubuntu@vm:~/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow$ ./convert.py examples/mnist/lenet.prototxt --caffemodel examples/mnist/lenet_iter_10000.caffemodel --data-output-path=mynet.npy
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./convert.py", line 60, in <module>
    main()
  File "./convert.py", line 56, in main
    args.phase)
  File "./convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 231, in load
    graph = DataInjector(def_path, data_path)(graph)
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/transformers.py", line 29, in __init__
    self.load()
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/transformers.py", line 33, in load
    self.load_using_caffe()
  File "/home/ubuntu/workspace/08_fine_train/fine-tune-alexnet/caffe-tensorflow/kaffe/transformers.py", line 39, in load_using_caffe
    net = caffe.Net(self.def_path, self.data_path, caffe.TEST)
AttributeError: 'module' object has no attribute 'Net'

**Comment by myth01** [comment]
How have you solved 
AttributeError: module 'caffe' has no attribute 'proto'

**Comment by shreyaspimpalgaonkar** [comment]
try pip install protobuf

**Comment by Jeep-Z** [comment]
@dinglong1020 How do you fixed
AttributeError: 'module' object has no attribute 'proto'?

**Comment by Jeep-Z** [comment]
@dinglong1020 How did you fix "AttributeError: 'module' object has no attribute 'proto'"?

**Comment by vishal83** [comment]
Also, @dinglong1020 How did you fix "AttributeError: 'caffe' has no attribute 'proto'"?
