### ISSUE TITLE
What version of tensorflow is supported? & convert googlenet model error

### ISSUE THREAD

**Issue by PieBoo** [ethereon/caffe-tensorflow#165]
1. What version of tensorflow does "caffe-tensorflow code" support ?
2. How to solve the convert error like below? 
I tried TensorFlow 1.3 and TensorFlow 1.6 environment to convert [Caffe googleNet model](https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet) to TensorFlow model.
Run the "caffe to tensorflow code", using below command: 
`./convert.py 20180327_test/GoogleNet/deploy.prototxt --caffemodel 20180327_test/GoogleNet/bvlc_googlenet.caffemodel --data-output-path=googleNetTensorflow.npy`
But I got the error below: 
> Traceback (most recent call last):
>   File "./convert.py", line 60, in <module>
>     main()
>   File "./convert.py", line 56, in main
>     args.phase)
>   File "./convert.py", line 27, in convert
>     transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
>   File "/home/miis/Documents/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in __init__
>     self.load(def_path, data_path, phase)
>   File "/home/miis/Documents/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 227, in load
>     graph = GraphBuilder(def_path, phase).build()
>   File "/home/miis/Documents/caffe-tensorflow/kaffe/graph.py", line 140, in __init__
>     self.load()
>   File "/home/miis/Documents/caffe-tensorflow/kaffe/graph.py", line 146, in load
>     text_format.Merge(def_file.read(), self.params)
>   File "/home/miis/tensorflow/lib/python2.7/site-packages/google/protobuf/text_format.py", line 533, in Merge
>     descriptor_pool=descriptor_pool)
>   File "/home/miis/tensorflow/lib/python2.7/site-packages/google/protobuf/text_format.py", line 587, in MergeLines
>     return parser.MergeLines(lines, message)
>   File "/home/miis/tensorflow/lib/python2.7/site-packages/google/protobuf/text_format.py", line 620, in MergeLines
>     self._ParseOrMerge(lines, message)
>   File "/home/miis/tensorflow/lib/python2.7/site-packages/google/protobuf/text_format.py", line 635, in _ParseOrMerge
>     self._MergeField(tokenizer, message)
>   File "/home/miis/tensorflow/lib/python2.7/site-packages/google/protobuf/text_format.py", line 679, in _MergeField
>     name = tokenizer.ConsumeIdentifierOrNumber()
>   File "/home/miis/tensorflow/lib/python2.7/site-packages/google/protobuf/text_format.py", line 1152, in ConsumeIdentifierOrNumber
>     raise self.ParseError('Expected identifier or number, got %s.' % result)
> google.protobuf.text_format.ParseError: 7:1 : Expected identifier or number, got <.

**Comment by dinglong1020** [comment]
convert bvlc_googlenet.caffemodel is ok on tensorflow 1.6
