### ISSUE TITLE
google.protobuf.text_format.ParseError: 7:1 : Expected identifier or number, got <.

### ISSUE THREAD

**Issue by shivansh2524** [ethereon/caffe-tensorflow#175]
I am trying to convert googlenet pretrained on places365 dataset and getting the following error.
`
----------------------------------------------------------
    WARNING: PyCaffe not found!
    Falling back to a pure protocol buffer implementation.
    * Conversions will be drastically slower.
    * This backend is UNTESTED!
------------------------------------------------------------

Traceback (most recent call last):
  File "convert.py", line 60, in <module>
    main()
  File "convert.py", line 56, in main
    args.phase)
  File "convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/vsl5/Desktop/shivansh/internship/caffe2tf/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/vsl5/Desktop/shivansh/internship/caffe2tf/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/vsl5/Desktop/shivansh/internship/caffe2tf/caffe-tensorflow/kaffe/graph.py", line 140, in __init__
    self.load()
  File "/home/vsl5/Desktop/shivansh/internship/caffe2tf/caffe-tensorflow/kaffe/graph.py", line 146, in load
    text_format.Merge(def_file.read(), self.params)
  File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 706, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 1166, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number, got %s.' % result)
google.protobuf.text_format.ParseError: 7:1 : Expected identifier or number, got <.
`
I am using python2.7 with tensorflow 1.8.0
Is there a fix for this probelm?

**Comment by JiangYi0311** [comment]
could you tell me how to solve this problem in detail? thanks.

**Comment by ravi0531rp** [comment]
Has anyone solved this??

**Comment by aliakbar09a** [comment]
I am facing the same problem.

**Comment by maxsim-memetu** [comment]
I ran into this issue when downloading alexnet prototxt by wget from this url:
`wget https://github.com/BVLC/caffe/blob/master/models/bvlc_alexnet/deploy.prototxt`

the downloaded prototxt was an html file and so incurs a parser complaint.
I circumvented this issue by coping the raw contents from github and pasting them into an empty file.
It worked out. 
Not sure if your problem has the same root cause.

**Comment by fridex** [comment]
> the downloaded prototxt was an html file and so incurs a parser complaint.

You can click on the "Raw" button to get raw file (without GitHub's html):

https://raw.githubusercontent.com/BVLC/caffe/master/models/bvlc_alexnet/deploy.prototxt

**Comment by ozlemalci** [comment]
google.protobuf.text_format.ParseError: 7:1 : '<!DOCTYPE html>': Expected identifier or number, got <.

I had the same problem. How do I solve it? Please help

**Comment by ozlemalci** [comment]
> 
> ## I am trying to convert googlenet pretrained on places365 dataset and getting the following error.
> `
> 
> ```
> WARNING: PyCaffe not found!
> Falling back to a pure protocol buffer implementation.
> * Conversions will be drastically slower.
> * This backend is UNTESTED!
> ```
> 
> Traceback (most recent call last):
> File "convert.py", line 60, in
> main()
> File "convert.py", line 56, in main
> args.phase)
> File "convert.py", line 27, in convert
> transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
> File "/home/vsl5/Desktop/shivansh/internship/caffe2tf/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in **init**
> self.load(def_path, data_path, phase)
> File "/home/vsl5/Desktop/shivansh/internship/caffe2tf/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 227, in load
> graph = GraphBuilder(def_path, phase).build()
> File "/home/vsl5/Desktop/shivansh/internship/caffe2tf/caffe-tensorflow/kaffe/graph.py", line 140, in **init**
> self.load()
> File "/home/vsl5/Desktop/shivansh/internship/caffe2tf/caffe-tensorflow/kaffe/graph.py", line 146, in load
> text_format.Merge(def_file.read(), self.params)
> File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 536, in Merge
> descriptor_pool=descriptor_pool)
> File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 590, in MergeLines
> return parser.MergeLines(lines, message)
> File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 623, in MergeLines
> self._ParseOrMerge(lines, message)
> File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
> self._MergeField(tokenizer, message)
> File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 706, in _MergeField
> name = tokenizer.ConsumeIdentifierOrNumber()
> File "/home/vsl5/anaconda3/envs/pyth2_7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 1166, in ConsumeIdentifierOrNumber
> raise self.ParseError('Expected identifier or number, got %s.' % result)
> google.protobuf.text_format.ParseError: 7:1 : Expected identifier or number, got <.
> `
> I am using python2.7 with tensorflow 1.8.0
> Is there a fix for this probelm?

I had the same problem. did you solve?
