### ISSUE TITLE
Running into Assertion Error

### ISSUE THREAD

**Issue by divyanshpal** [ethereon/caffe-tensorflow#185]
I am trying to convert a caffee model to tf and run into following  error.
Traceback (most recent call last):
  File "convert.py", line 68, in <module>
    main()
  File "convert.py", line 64, in main
    args.phase)
  File "convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/divyansh/face_recognition/caffe2tf/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/divyansh/face_recognition/caffe2tf/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/divyansh/face_recognition/caffe2tf/caffe-tensorflow/kaffe/graph.py", line 209, in build
    layers = self.filter_layers(layers)
  File "/home/divyansh/face_recognition/caffe2tf/caffe-tensorflow/kaffe/graph.py", line 168, in filter_layers
    assert layer.name not in filtered_layer_names
AssertionError

**Comment by tanndx17** [comment]
hi, did you solve the problem? I met a similar issue, but another layer name not in graph

**Comment by PonderK** [comment]
@tanndx17 @divyanshpal hello, i have the same error with yours, do you have any solution?

**Comment by tanndx17** [comment]
@PonderK Not yet, I guess it's the op naming issue in tensorflow

**Comment by cevatarmutlu** [comment]
hi, did you solve the problem?

**Comment by vanessawei726** [comment]
I ran into the same question of yours and wondered if anyone found the solution
