### ISSUE TITLE
TypeError: unsupported format string passed to tuple.__format__

### ISSUE THREAD

**Issue by aliakbar09a** [ethereon/caffe-tensorflow#186]
I am trying to convert a caffe model to tensorflow model. Here is the error :

Traceback (most recent call last):
  File "convert.py", line 60, in <module>
    main()
  File "convert.py", line 56, in main
    args.phase)
  File "convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/ali/Desktop/Projects/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/home/ali/Desktop/Projects/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 254, in load
    print_stderr(self.graph)
  File "/home/ali/Desktop/Projects/caffe-tensorflow/kaffe/errors.py", line 7, in print_stderr
    sys.stderr.write('%s\n' % msg)
  File "/home/ali/Desktop/Projects/caffe-tensorflow/kaffe/graph.py", line 125, in __str__
    tuple(out_shape)))
TypeError: unsupported format string passed to tuple.__format__

**Comment by la735681253** [comment]
i meet the same problem. do you salve it？

**Comment by aliakbar09a** [comment]
No, but if you are looking for conversion between different models check out [mmdnn ](https://github.com/microsoft/MMdnn)repo by Microsoft.

**Comment by AbhorsenKnight** [comment]
Hi, I solved the problem by changing to Python 2.7. Hope this helps.
