### ISSUE TITLE
Can't Convert Example

### ISSUE THREAD

**Issue by jsl303** [ethereon/caffe-tensorflow#188]
I tried to convert a caffe model, but I got an error. I tried convert the provided example, and I got the same error below.

Python 3.7.4
caffe 1.0.0
tensorflow 1.14.0
>>>
$ python convert.py examples/mnist/lenet.prototxt --code-output-path=mynet.py
Traceback (most recent call last):
  File "convert.py", line 60, in <module>
    main()
  File "convert.py", line 56, in main
    args.phase)
  File "convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/mnt/e/Programming/python/ml/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/mnt/e/Programming/python/ml/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 254, in load
    print_stderr(self.graph)
  File "/mnt/e/Programming/python/ml/caffe-tensorflow-master/kaffe/errors.py", line 7, in print_stderr
    sys.stderr.write('%s\n' % msg)
  File "/mnt/e/Programming/python/ml/caffe-tensorflow-master/kaffe/graph.py", line 125, in __str__
    tuple(out_shape)))
TypeError: unsupported format string passed to tuple.__format__

**Comment by KyleBan** [comment]
Hi, I have the same problem and I do not know how to solve that. Have you solve that yet?

**Comment by YCakira** [comment]
这是来自QQ邮箱的自动回复邮件。嗨，这里是吴颖的信箱。谢谢你的来信，我将会尽快给你回复。
