### ISSUE TITLE
Not support variable batch size?

### ISSUE THREAD

**Issue by joelthchao** [ethereon/caffe-tensorflow#21]
During graph construction, network should not be able to know the batch size (the first dimension of tensor). I have made some modifications to deal with this problem, not sure if you need to support this feature.

**Comment by pkmital** [comment]
What did you modify to support this?

**Comment by joelthchao** [comment]
In `netwwork.py`

1. Remove unnecessary reshaping after `bias_add`
2. Reshape fc `feed_in` with `shape=[-1, dim]`

Then you can feed your network with `tf.placeholder(tf.float32, shape=[None, height, width, channel])`

**Comment by vodp** [comment]
Applying your patch, I am able to load LeNet with None in batch_size but failed in testing with `caffe-tensorflow/examples/vgg.py`
```
>>> from vgg import VGG16
>>> import tensorflow as tf
>>> x = tf.placeholder(tf.float32, [None, 224, 224, 3])
>>> y = tf.placeholder(tf.float32, [None, 1000])
>>> net = VGG16({'data': x})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "kaffe/tensorflow/network.py", line 37, in __init__
    self.setup()
  File "vgg.py", line 6, in setup
    .conv(3, 3, 64, 1, 1, name='conv1_1')
  File "kaffe/tensorflow/network.py", line 20, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "kaffe/tensorflow/network.py", line 108, in conv
    bias = tf.reshape(tf.nn.bias_add(conv, biases), conv.get_shape().as_list())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1202, in reshape
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 445, in apply_op
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 565, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 343, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 281, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got None of type '_Message' instead.
```

**Comment by vodp** [comment]
Thanks for the trick! Do you know which modifications could be made to enable variable image size?

**Comment by joelthchao** [comment]
@vodp variable image size will result in non-determined network size, unless you are dealing with fully convolutional neural network. You will need to use pure TensorFlow to define your model.

**Comment by ethereon** [comment]
For posterity: the current version should work fine with variable batch sizes.
