### ISSUE TITLE
Message type "caffe.NetParameter" has no field named "mean_value"

### ISSUE THREAD

**Issue by ZhuFengdaaa** [ethereon/caffe-tensorflow#24]
I want to convert googlenet v2 to tensorflow code. The traceback is shown as follows: 
 
      $ ./convert.py train_val.prototxt googlenet_bn.caffemodel data.out source.out

```
Traceback (most recent call last):
  File "./convert.py", line 35, in <module>
    main()
  File "./convert.py", line 19, in main
    transformer = TensorFlowTransformer(args.def_path, args.data_path, phase=args.phase)
  File "/home/zhufengda/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 188, in __init__
    self.load(def_path, data_path, phase)
  File "/home/zhufengda/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 192, in load
    self.graph = GraphBuilder(def_path, data_path, phase).build()
  File "/home/zhufengda/caffe-tensorflow/kaffe/core.py", line 250, in __init__
    self.load()
  File "/home/zhufengda/caffe-tensorflow/kaffe/core.py", line 255, in load
    text_format.Merge(def_file.read(), self.params)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 309, in Merge
    return MergeLines(text.split('\n'), message, allow_unknown_extension)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 346, in MergeLines
    _ParseOrMerge(lines, message, True, allow_unknown_extension)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 371, in _ParseOrMerge
    allow_unknown_extension)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 443, in _MergeField
    message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 1:1 : Message type "caffe.NetParameter" has no field named "mean_value".
```

The only key that named `mean_value` is the first three lines of `train_val.prototxt`

**Comment by ethereon** [comment]
Could you please double-check that the prototxt is in the latest format, as described in the readme?
