### ISSUE TITLE
Can't run convert.py

### ISSUE THREAD

**Issue by slundqui** [ethereon/caffe-tensorflow#35]
I seem to get an import error when I try running convert.py:

Traceback (most recent call last):
  File "convert.py", line 7, in <module>
    from kaffe import KaffeError, print_stderr
  File "/home/sheng/workspace/caffe-tensorflow/kaffe/__init__.py", line 1, in <module>
    from .graph import GraphBuilder, NodeMapper
  File "/home/sheng/workspace/caffe-tensorflow/kaffe/graph.py", line 4, in <module>
    from .data import DataInjector
ImportError: No module named data

I'm running Anaconda python 2.7, if that helps. Any help would be appreciated.

**Comment by ethereon** [comment]
Looks like a bit of stray import left over after the last refactor. I've pushed a new commit that should fix it.

**Comment by slundqui** [comment]
Much thanks, got it to work.
