### ISSUE TITLE
Protobuf  error?

### ISSUE THREAD

**Issue by Arsakes** [ethereon/caffe-tensorflow#75]
**Trying to use caffe-tensorflow on squezze net:**

`./convert.py ./SqueezeNet_v1.1/train_val.prototxt --caffemodel=./SqueezeNet_v1.1/squeezenet_v1.1.caffemodel --data-output-path=./squezze.npy`

**I'm getting following error:**

```
....
  File "/home/pietrko/firma/deep_learning/tools/caffe-tensorflow/kaffe/caffe/resolver.py", line 13, in import_caffe
    import caffe
ImportError: No module named 'caffe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1080, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1102, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/usr/lib/python3.5/site-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./convert.py", line 61, in <module>
    main()
  File "./convert.py", line 57, in main
    args.phase)
  File "./convert.py", line 28, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/home/pietrko/firma/deep_learning/tools/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 222, in __init__
    self.load(def_path, data_path, phase)
  File "/home/pietrko/firma/deep_learning/tools/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 228, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/pietrko/firma/deep_learning/tools/caffe-tensorflow/kaffe/graph.py", line 140, in __init__
    self.load()
  File "/home/pietrko/firma/deep_learning/tools/caffe-tensorflow/kaffe/graph.py", line 144, in load
    self.params = get_caffe_resolver().NetParameter()
  File "/home/pietrko/firma/deep_learning/tools/caffe-tensorflow/kaffe/caffe/resolver.py", line 32, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "/home/pietrko/firma/deep_learning/tools/caffe-tensorflow/kaffe/caffe/resolver.py", line 7, in __init__
    self.import_caffe()
  File "/home/pietrko/firma/deep_learning/tools/caffe-tensorflow/kaffe/caffe/resolver.py", line 17, in import_caffe
    from . import caffepb
  File "/home/pietrko/firma/deep_learning/tools/caffe-tensorflow/kaffe/caffe/caffepb.py", line 799, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  File "/usr/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 850, in _ParseOptions
    message.ParseFromString(string)
  File "/usr/lib/python3.5/site-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1086, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
```

**Comment by Arsakes** [comment]
Delete this it probably due to the python3 being used..
