### ISSUE TITLE
ValueError on VGG Places2 model

### ISSUE THREAD

**Issue by dcaulfield** [ethereon/caffe-tensorflow#8]
Hi,

I tried to convert the VGG model for the Places2 dataset (from [here] (http://places2.csail.mit.edu/download.html)). But I get the following error:

```
(tensorflow)AIs-MacBook-Pro:caffe-tensorflow-master AI$ ./convert.py deploy.prototxt vgg16_places2.caffemodel placesnet.npy placesnet.py
WARNING: PyCaffe not found!
Falling back to protocol buffer implementation.
This may take a couple of minutes.
Traceback (most recent call last):
  File "./convert.py", line 33, in <module>
    main()
  File "./convert.py", line 17, in main
    transformer = TensorFlowTransformer(def_path, data_path)
  File "/Users/AI/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 184, in __init__
    self.load(def_path, data_path)
  File "/Users/AI/caffe-tensorflow-master/kaffe/tensorflow/transformer.py", line 188, in load
    self.graph = GraphBuilder(def_path, data_path).build()
  File "/Users/AI/caffe-tensorflow-master/kaffe/core.py", line 308, in build
    DataInjector(self.def_path, self.data_path).inject(graph)
  File "/Users/AI/caffe-tensorflow-master/kaffe/core.py", line 118, in __init__
    self.load()
  File "/Users/AI/caffe-tensorflow-master/kaffe/core.py", line 127, in load
    self.load_using_pb()
  File "/Users/AI/caffe-tensorflow-master/kaffe/core.py", line 140, in load_using_pb
    self.params = [pair(layer) for layer in layers if layer.blobs]
  File "/Users/AI/caffe-tensorflow-master/kaffe/core.py", line 138, in <lambda>
    pair = lambda layer: (layer.name, self.transform_data(layer))
  File "/Users/AI/caffe-tensorflow-master/kaffe/core.py", line 149, in transform_data
    data = np.squeeze(np.array(blob.data, dtype=np.float32).reshape(c_o, c_i, h, w))
ValueError: total size of new array must be unchanged
```

This seems to be the same issue as [here] (https://github.com/ethereon/caffe-tensorflow/issues/6?_pjax=%23js-repo-pjax-container). Is there any workaround that I can use?

Thanks

**Comment by rejuvyesh** [comment]
```
Type                 Name                                          Param               Output
----------------------------------------------------------------------------------------------
Data                 data                                             --     (1, 3, 224, 224)
Convolution          conv1_1                               (64, 3, 3, 3)    (1, 64, 224, 224)
Convolution          conv1_2                              (64, 64, 3, 3)    (1, 64, 224, 224)
Pooling              pool1                                            --    (1, 64, 112, 112)
Convolution          conv2_1                             (128, 64, 3, 3)   (1, 128, 112, 112)
Convolution          conv2_2                            (128, 128, 3, 3)   (1, 128, 112, 112)
Pooling              pool2                                            --     (1, 128, 56, 56)
Convolution          conv3_1                            (256, 128, 3, 3)     (1, 256, 56, 56)
Convolution          conv3_2                            (256, 256, 3, 3)     (1, 256, 56, 56)
Convolution          conv3_3                            (256, 256, 3, 3)     (1, 256, 56, 56)
Pooling              pool3                                            --     (1, 256, 28, 28)
Convolution          conv4_1                            (512, 256, 3, 3)     (1, 512, 28, 28)
Convolution          conv4_2                            (512, 512, 3, 3)     (1, 512, 28, 28)
Convolution          conv4_3                            (512, 512, 3, 3)     (1, 512, 28, 28)
Pooling              pool4                                            --     (1, 512, 14, 14)
Convolution          conv5_1                            (512, 512, 3, 3)     (1, 512, 14, 14)
Convolution          conv5_2                            (512, 512, 3, 3)     (1, 512, 14, 14)
Convolution          conv5_3                            (512, 512, 3, 3)     (1, 512, 14, 14)
Pooling              pool5                                            --       (1, 512, 7, 7)
InnerProduct         fc6                                   (4096, 25088)      (1, 4096, 1, 1)
InnerProduct         fc7                                    (4096, 4096)      (1, 4096, 1, 1)
InnerProduct         fc8                                     (401, 4096)       (1, 401, 1, 1)
Softmax              prob                                             --       (1, 401, 1, 1)
Converting data...
Saving data...
Saving source...
Done.
```

So it works using `pycaffe`. You just need to add caffe to your `$PYTHONPATH`.

**Comment by ethereon** [comment]
There was a bug in the fallback parser (used when PyCaffe's not found) that caused this. I just pushed a fix that should resolve this issue.
