### ISSUE TITLE
ValueError: Variable conv5_1/weights does not exist, or was not created with tf.get_variable(). 

### ISSUE THREAD

**Issue by Angela931228** [ethereon/caffe-tensorflow#85]
I upgrade the vgg caffe model and successfully converted the model and weight file.However,
when I run the classification 

./classify_vgg.py  vgg.npy  dog.jpg 

It encountered the following error:
Traceback (most recent call last):
  File "classify_vgg.py", line 78, in <module>
    main()
  File "classify_vgg.py", line 74, in main
    classify(args.model_path, args.image_paths)
  File "classify_vgg.py", line 51, in classify
    net.load(model_data_path, sesh)
  File "/home/angelazhou/tensorflow/test/caffe-tensorflow/kaffe/tensorflow/network.py", line 66, in load
    var = tf.get_variable(param_name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 650, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable conv5_1/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by woodysong** [comment]
Hi there, has you figured out how to deal with it? I'm just at the same situation. Thanks.

**Comment by Angela931228** [comment]
you mean ValueError: Variable conv5_1/weights does not exist, or was not created with tf.get_variable().?
I was converting googlenet. The model and the weight file are right. but in classify.py. I forgot to change the models.get_data_spec(model_class=models.GoogleNet) and net = models.GoogleNet({'data': input_node}).

In case that you have "KeyError: 'Unknown layer name fed: input“ 
you can change to net = models.GoogleNet({'input': input_node}) in classify.py
or change  to self.feed('input') in models/googlenet.py

Hope it can help you.

**Comment by woodysong** [comment]
Oh yes, you're right! I just missed it. Thanks.
